//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class czlonkowie
    {
        public int id_czlonkostwa { get; set; }
        public int id_grupy { get; set; }
        public int id_uzytkownika { get; set; }
    
        public virtual grupy grupy { get; set; }
        public virtual uzytkownicy_login uzytkownicy_login { get; set; }
    }
}
