//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupy
    {
        public grupy()
        {
            this.czlonkowies = new HashSet<czlonkowie>();
            this.kategories = new HashSet<kategorie>();
            this.quizs = new HashSet<quiz>();
        }
    
        public int id_grupy { get; set; }
        public int id_administratora { get; set; }
        public string nazwa { get; set; }
        public sbyte prywatnosc { get; set; }
        public Nullable<System.DateTime> data_zalozenia { get; set; }
    
        public virtual ICollection<czlonkowie> czlonkowies { get; set; }
        public virtual uzytkownicy_login uzytkownicy_login { get; set; }
        public virtual ICollection<kategorie> kategories { get; set; }
        public virtual ICollection<quiz> quizs { get; set; }
    }
}
