//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategorie
    {
        public kategorie()
        {
            this.pytanias = new HashSet<pytania>();
            this.quizs = new HashSet<quiz>();
        }
    
        public int id_kategorii { get; set; }
        public int id_grupy { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
    
        public virtual grupy grupy { get; set; }
        public virtual ICollection<pytania> pytanias { get; set; }
        public virtual ICollection<quiz> quizs { get; set; }
    }
}
