//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class pytania
    {
        public pytania()
        {
            this.quiz_pytania = new HashSet<quiz_pytania>();
            this.statystyki_szczegolowe = new HashSet<statystyki_szczegolowe>();
        }
    
        public int id_pytania { get; set; }
        public int id_kategorii { get; set; }
        public int id_uzytkownika { get; set; }
        public string tresc { get; set; }
        public string odpowiedz1 { get; set; }
        public string odpowiedz2 { get; set; }
        public string odpowiedz3 { get; set; }
        public string odpowiedz4 { get; set; }
        public sbyte indeks_poprawnej { get; set; }
    
        public virtual kategorie kategorie { get; set; }
        public virtual ICollection<quiz_pytania> quiz_pytania { get; set; }
        public virtual uzytkownicy_login uzytkownicy_login { get; set; }
        public virtual ICollection<statystyki_szczegolowe> statystyki_szczegolowe { get; set; }
    }
}
