//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class statystyki_glowne
    {
        public int id_statystyki { get; set; }
        public int id_quizu { get; set; }
        public int poprawne { get; set; }
        public int niepoprawne { get; set; }
        public Nullable<System.DateTime> czas_rozpoczecia { get; set; }
        public Nullable<System.DateTime> czas_zakonczenia { get; set; }
    
        public virtual quiz quiz { get; set; }
    }
}
