//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownicy_info
    {
        public int id_info { get; set; }
        public int id_login { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string plec { get; set; }
        public string adres_email { get; set; }
        public Nullable<System.DateTime> data_urodzenia { get; set; }
        public Nullable<System.DateTime> data_rejestracji { get; set; }
    
        public virtual uzytkownicy_login uzytkownicy_login { get; set; }
    }
}
