//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownicy_login
    {
        public uzytkownicy_login()
        {
            this.czlonkowies = new HashSet<czlonkowie>();
            this.grupies = new HashSet<grupy>();
            this.pytanias = new HashSet<pytania>();
            this.quizs = new HashSet<quiz>();
            this.uzytkownicy_info = new HashSet<uzytkownicy_info>();
        }
    
        public int id_login { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
    
        public virtual ICollection<czlonkowie> czlonkowies { get; set; }
        public virtual ICollection<grupy> grupies { get; set; }
        public virtual ICollection<pytania> pytanias { get; set; }
        public virtual ICollection<quiz> quizs { get; set; }
        public virtual ICollection<uzytkownicy_info> uzytkownicy_info { get; set; }
    }
}
